import './assets/scss/main.scss'
import './assets/components/dropdown/dropdown'
import './assets/components/likeButton/likeButton'
import './assets/components/range/range'
import './assets/components/guestDropdown/guestDropdown'
import './assets/components/roomDropdown/roomDropdown'

import './assets/components/slider/slider'
// import './assets/components/datepicker/datepicker'
import './assets/components/rateButton/rateButton'
